import React from 'react';
import Collapsible from './Collapsible';
import styled from 'styled-components';

export default function Faq(props){
  return (
    <Wrapper>
      <h2>Frequently Asked Questions</h2>
      <Collapsible summary="What is Chiffon?">
        Chiffon is a game engine built specifically for creating dress-up games.
        Anyone can use Chiffon to build a game using only a directory of images.
        Chiffon is open source and released under the MIT license. There's no
        need to download Chiffon's source code to use the engine, but if you'd
        like to explore the source code, you can find the code repository <a href="https://github.com/ncreel/chiffonJS">on Github</a>
      </Collapsible>
      <Collapsible summary="How do I use Chiffon?">
        blah blah blah
      </Collapsible>
      <Collapsible summary="How do I create assets?">
        something here about GIMP, photoshop, other art tools, all photos need
        to be .pngs and need to be the same size.
      </Collapsible>
      <Collapsible summary="What can I do with the generated Chiffon game?">
        The game generated by chiffon can be deployed using any web server
        that supports Javascript. Itch.io is a great way to upload HTML games to
        the web (You may use the generated Chiffon game for commercial purposes).
      </Collapsible>
    </Wrapper>
  )
}

const Wrapper = styled.section`
  h2{
    margin: 0px;
    color: hsl(332, 96%, 44%);
    font-size: 1.75rem;
    font-family: 'Leckerli One', cursive;
    text-align: center;
  }
  & a{
    color:#83b314;
  }
  & a:hover{
    background-color:#dc0469;
    font-weight:700;
    color:#b3da58
    cursor: pointer;
  }
`
